### ISSUE TITLE
Strange behavior or?

### ISSUE THREAD

**Issue by djhojd** [gintas/django-picklefield#10]
# models
    class Order(models.Model):
        details = PickledObjectField()

    # view
    data = {'test': 0}
    o = Order.objects.create(details=data)
    print o.details # {'test': 0}

    data['test'] = 1
    print o.details # {'test': 1}
    
Is the second print result correct?

PS: I'm have under 1year of django/python so maybe I'm missing something here.

**Comment by charettes** [comment]
This is the expected behavior since `o.details is data`.
