### ISSUE TITLE
ModuleNotFoundError: No module named 'django' on installing dependencies

### ISSUE THREAD

**Issue by skinderis** [gintas/django-picklefield#43]
I am using wercker to build env, install dependencies and run project. Trying to use this repo, but I get an error:

```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kx65qy6n/picklefield/setup.py", line 5, in <module>
        import picklefield
      File "/tmp/pip-build-kx65qy6n/picklefield/picklefield/__init__.py", line 3, in <module>
        import django.utils.version
    ModuleNotFoundError: No module named 'django'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kx65qy6n/picklefield/
```

This error happens because on [setup.py](https://github.com/gintas/django-picklefield/blob/master/setup.py#L5) file it import **pickledfield** dir which is importing django module on initiation. And then I get this error. 

Is there any way I can solve this issue?

**Comment by DylanYoung** [comment]
Install django?

**Comment by charettes** [comment]
Right. Installing `django` should do and this is less likely to be an issue if you update your `pip` version so it will install the wheel instead of the source package.
