### ISSUE TITLE
Queryset.query not pickled correctly when saving PickledObjectField since Django 3.0

### ISSUE THREAD

**Issue by flokain** [gintas/django-picklefield#48]
trying to pickle a Query object.
it seems like the default values is not being serialized:

DB is postgres 10.1
django 3.0.3
python 3.7.4

` eligible_team_query = PickledObjectField(default=Team.objects.all().query)`

```
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.SyntaxError: subquery must return only one column
LINE 1: ...query", "eligible_team_query") VALUES ('u17', '', (SELECT "p...
```

_Originally posted by @flokain in https://github.com/gintas/django-picklefield/issues/47#issuecomment-588190697_

**Comment by charettes** [comment]
I'm afraid there's very little we'll be able to do as we want to keep allowing the usage of expressions in `Field.default`. In other words special casing expressions in `PickledObjectField.get_default` would prevent stuff like `default=F('other_pickled_field')`. Django 3.0 just happened to make `django.db.models.sql.Query` an expression which is what causing your crash here.

I assume the following works just fine?

```python
def default_eligible_team_query(self):
    return dbsafe_encode(Team.objects.all().query)

eligible_team_query = PickledObjectField(default=default_eligible_team_query)
```

**Comment by flokain** [comment]
yes this works. thank you!

**Comment by charettes** [comment]
Alright I'll close the issue then as there's little `django-picklefield` can do about passing ORM internal objects to the ORM.
