### ISSUE TITLE
Cannot use PickleField to save a QuerySet query

### ISSUE THREAD

**Issue by bmampaey** [gintas/django-picklefield#55]
This is such a particular case that I do not expect it to be solved... and actually one could argue that the bug is in the Django library.

Django specifies that if you want to pickle a QuerySet, you must pickle the query 
https://docs.djangoproject.com/en/3.2/ref/models/querysets/#pickling-querysets

The problem is that a query has a method "resolve_expression", and in that case, Django skip the call to get_db_prep_save.
https://github.com/django/django/blob/3.0.14/django/db/models/sql/compiler.py#L1257

get_db_prep_save in turn is supposed to call get_db_prep_value responsible for the pickling of the object
https://github.com/django/django/blob/3.0.14/django/db/models/fields/__init__.py#L819

As a result the query object is not pickled, and Django throws an error because it creates a sub select in the query, etc.

**Comment by charettes** [comment]
yeah I don't think it's worth fixing that one. One could wrap the `QuerySet` in a list or other object to avoid the `resolve_expression` trip.
