### ISSUE TITLE
RuntimeWarning: Pickled model instance's Django version

### ISSUE THREAD

**Issue by manuelcua** [gintas/django-picklefield#59]
I´m getting this warning when I updated Django, what should I do? load and save all my models PickedField? 

/venv/lib/python3.8/site-packages/picklefield/fields.py:78: RuntimeWarning: Pickled model instance's Django version 3.1.7 does not match the current version 3.2.6.

**Comment by charettes** [comment]
This warning has little to do with this project but more about _what_ you stored in it.

[Refer to Django's documentation](https://docs.djangoproject.com/en/3.2/ref/models/instances/#pickling-objects) about the gotchas of pickling `Model` instances between Django versions.
